### PR TITLE
Add scss support for "tab" hotkey

### PR DESCRIPTION
**Pull request by dslpp056193**
Every update i change this line in my emmet package for atom.
I think for somebody it will be useful.

### CODE REVIEW

**Comment by sergeche** [comment]
You don’t have to modify Emmet package, there’s “Your keymap” file for customizing such things

**Comment by dslpp056193** [comment]
But why you added "sass", and don't add "scss"?
CSS cuts very useful in scss code. Why it's can't be default?

**Comment by sergeche** [comment]
Just forgot to add it. And FYI, default grammar for default SCSS highlighter is `source css scss`, which is matched by already-existing `atom-text-editor[data-grammar~="css"]:not([mini])` selector and it works fine for me. Not sure why you had problems with it.

**Comment by dslpp056193** [comment]
But why you added "sass", and don't add "scss"?
CSS cuts very useful in scss code. Why it's can't be default?

**Comment by dslpp056193** [comment]
Thanks, i don't know why my atom can't init emmet inside scss code.

**Pull request merged**
